### ISSUE TITLE
Advice: implementing strict mode in Javascript code

### ISSUE THREAD

**Issue by ytxmobile98** [wongchito/GenRailMap#1]
The **strict mode** aims to normalize and restrict the behavior of JavaScript code in several aspects, which can make your code more robust and less prone to errors:

1. In many situations, it explicitly throws errors (visible in the console) to notify the programmer and/or users about certain statements that would produce silent errors in non-strict mode. This can reduce the difficulty and save time in debugging runtime errors, as well as preventing unsafe actions. For example, you can no longer accidentally create global variables, overwrite non-writable object properties, or extending a non-configurable object without knowing that an error is thrown.
2. It fixes some mistakes that make the JS engine difficult to perform optimizations. For this reason, strict-mode codes sometimes have better performance than non-strict-mode codes.
3. It prevents the use of certain syntax that may be introduced to ECMAscript in the future, such as `implements`, `extends`, `interface`, `public`, `private`, etc.

For more details, refer to:
* [MDN: strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)
* [GeeksForGeeks: strict mode in JavaScript](https://www.geeksforgeeks.org/strict-mode-javascript/)

**Comment by wongchito** [comment]
Thanks for your advice, ytx21cn! Since I’m new to JS, I don’t have much experience of writing JS code and don’t know much about the behaviour of using “strict mode” or not. But anyway, I will look into it and consider implementing the strict mode.

**Comment by wongchito** [comment]
Hi ytx21cn! The strict mode is now implemented and this issue is closed.
